version: '3.8'
services:
  server:
    build: ./server
    container_name: server
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M